AWSTemplateFormatVersion: 2010-09-09
Resources:
  htmlbucketID:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      BucketName: ruscty-bucket-html
      MetricsConfigurations:
        - Id: HtmlBucketID
      Tags:
        - Key: management
          Value: dev
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true